export type Locale = 'en' | 'he'

export const RELEASES_URL = 'https://github.com/danik9444/EasyField/releases'
export const REPOSITORY_URL = 'https://github.com/danik9444/EasyField'

export const copy = {
  en: {
    languageLabel: 'עברית',
    nav: {
      product: 'Product',
      tools: '20 tools',
      workflow: 'Workflow',
      pricing: 'Pricing',
      faq: 'FAQ',
      cta: 'Get EasyField',
      menu: 'Open menu',
      close: 'Close menu',
    },
    hero: {
      eyebrow: 'PRIVATE BETA · COMPATIBLE WITH DAVINCI RESOLVE STUDIO 21',
      titleLead: 'AI plugin for Resolve 21.',
      titleAccent: 'Built around your timeline.',
      body: 'EasyField turns real edit context—playhead frames, visible trims, shot boundaries and Library assets—into reviewed image, video, motion and audio workflows, then returns only the result you approve.',
      secondary: 'Explore the workspace',
      note: 'macOS 15+ · Resolve Studio 21.0.2+ · Apple silicon & Intel',
      status: 'Release-aware download',
    },
    release: {
      checking: 'Checking latest build…',
      available: 'Download for macOS',
      unavailable: 'Follow the public release',
      unavailableShort: 'Release status',
      hintAvailable: 'Signed universal PKG',
      hintUnavailable: 'The public PKG is not published yet',
    },
    proof: [
      { value: '20', label: 'purpose-built tools' },
      { value: '5', label: 'creative categories' },
      { value: '100', label: 'local transcript languages' },
      { value: '1', label: 'continuous timeline flow' },
    ],
    product: {
      eyebrow: 'TIMELINE INTEGRATION',
      title: 'Exact context in. Deliberate placement out.',
      body: 'EasyField captures only the source and timing each workflow needs, preserves every artifact in the local Library and lets the editor control the final handoff.',
      labels: ['Exact visible trims', 'Review before placement', 'Local Library first'],
    },
    tools: {
      eyebrow: 'PURPOSE-BUILT, NOT PROMPT-BUILT',
      title: 'Twenty focused workflows. One familiar surface.',
      body: 'Move from footage review to images, generated shots, motion, narration, sound and timing without rebuilding context in another app.',
      categoryLabel: 'Tool category',
      availability: 'Availability depends on the installed build and verified adapters.',
      total: 'WORKFLOWS\n05 CATEGORIES',
      count: 'TOOLS',
      review: 'REVIEW',
      workspace: 'WORKSPACE',
    },
    workflow: {
      eyebrow: 'ONE CONTROLLED FLOW',
      title: 'Context in. Reviewed result out.',
      body: 'EasyField keeps the editor in charge at every step—from source selection to privacy and cost preflight to final placement.',
      steps: [
        { index: '01', title: 'Capture exact context', body: 'Use the current playhead, selected range, Media Pool, local file or an existing Library result.' },
        { index: '02', title: 'Direct the right workflow', body: 'Choose a recipe and verified model, then shape prompt, references, duration and output.' },
        { index: '03', title: 'Review before anything changes', body: 'See provider, privacy, estimated credits and placement intent before you run or apply.' },
        { index: '04', title: 'Keep it, then place it', body: 'Results land in your local Library first. Send only the chosen version back to Resolve.' },
      ],
    },
    brain: {
      eyebrow: 'SUPERBRAIN',
      title: 'A timeline strategist—not a black box.',
      body: 'Describe the outcome you want. SuperBrain turns it into a typed, reviewable multi-tool plan so you can inspect the steps before execution is enabled.',
      prompt: 'Build a 30-second trailer from the selected range. Keep the dialogue, add restrained captions, and suggest a score.',
      response: 'I mapped a three-part workflow around your selected range. Review sources, placement, privacy and estimated cost before running each tool.',
      plan: [
        ['01', 'Analyze the selected range', 'LOCAL'],
        ['02', 'Prepare a caption workflow', 'REVIEW'],
        ['03', 'Draft a custom score brief', 'CLOUD'],
      ],
      status: 'PLAN READY FOR REVIEW',
      badge: 'Nothing changes until you approve',
    },
    trust: {
      eyebrow: 'BUILT FOR REAL EDITS',
      title: 'Cloud where it helps. Local where it matters.',
      body: 'The product distinguishes local, hybrid and cloud workflows, protects Resolve access behind a localhost bridge, and keeps durable job and artifact records on your Mac.',
      cards: [
        { title: 'Private local work', body: 'Transcription and beat analysis are designed to run locally with reusable, managed runtimes.' },
        { title: 'Explicit cloud preflight', body: 'See what is uploaded, which provider is used and the estimated credits before a cloud task starts.' },
        { title: 'Non-destructive placement', body: 'Generated media is materialized and reviewed before it is imported or appended to the active timeline.' },
      ],
      footnote: 'Product availability and runtime packaging are release-dependent. EasyField never presents a paid task as completed when its adapter is unavailable.',
    },
    pricing: {
      eyebrow: 'LAUNCH PRICING PREVIEW',
      title: 'A plan for every edit room.',
      body: 'These are the product’s current planned plan values. Checkout is not enabled during the private beta.',
      monthly: 'Monthly',
      annual: 'Annual',
      perMonth: '/ month',
      perYear: '/ year',
      credits: 'credits each month',
      allModels: 'All verified model families',
      starterModels: 'Seedance 2 Fast & Mini; regular Seedance 2 excluded',
      topup: 'Top-ups from $10',
      library: 'Local Library & Activity',
      billingLabel: 'Billing interval',
      current: 'Recommended',
      beta: 'Available after public launch',
      partner: 'Partner preview: $999 one-time lifetime access, all verified models, and your own provider account. Not available in private beta.',
    },
    install: {
      eyebrow: 'READY FOR LAUNCH DAY',
      title: 'Install once. Stay in the flow.',
      body: 'When the notarized public build is published, the same download action on this page will automatically point to the latest universal macOS PKG.',
      steps: [
        { title: 'Download the universal PKG', body: 'One installer for Apple silicon and Intel, signed and notarized for macOS.' },
        { title: 'Close Resolve and install', body: 'The installer validates your OS and Resolve setup, then performs an atomic plugin installation.' },
        { title: 'Open EasyField in Resolve', body: 'Open a project and timeline, then choose Workspace → Workflow Integrations → EasyField.' },
      ],
      requirements: 'System requirements',
      requirementItems: ['macOS 15 or newer', 'DaVinci Resolve Studio 21.0.2+', 'Resolve installed directly from Blackmagic Design', 'Administrator permission during installation'],
      devNote: 'Node, Python, Homebrew and FFmpeg are development requirements—not end-user setup steps.',
    },
    faq: {
      eyebrow: 'QUESTIONS, ANSWERED',
      title: 'Before you put it on the timeline.',
      items: [
        { q: 'Is EasyField available to download today?', a: 'The website checks GitHub Releases live. Right now the public signed PKG has not been published, so the call to action opens the release status. As soon as a verified release exists, it automatically becomes a direct macOS download.' },
        { q: 'Does it work with the free version of DaVinci Resolve?', a: 'The current target is DaVinci Resolve Studio 21.0.2 or newer on macOS 15+. The Mac App Store build is not supported by the planned installer.' },
        { q: 'Does every tool upload my footage?', a: 'No. EasyField distinguishes local, hybrid and cloud workflows. Each run is designed to show a privacy and upload preflight before anything leaves your Mac.' },
        { q: 'Does SuperBrain edit my timeline automatically?', a: 'Not in the current product state. SuperBrain builds and validates a reviewed multi-tool plan. Applying a full plan remains gated until each step exposes cost, privacy, provider, placement and rollback contracts.' },
        { q: 'Where do generated results go?', a: 'Accepted results are materialized in the local EasyField Library first. You then choose what to download, send to the Media Pool or place on the active timeline.' },
        { q: 'Which tools are included?', a: 'The current catalog contains 20 workflows across Footage, Image, Video, Motion and Audio. Some newer workflows may stop at an honest preflight until their verified adapter is present in the installed build.' },
      ],
    },
    closing: {
      eyebrow: 'FROM IDEA TO FINAL TIMELINE',
      title: 'Keep the creative decision where it belongs—with the editor.',
      body: 'Follow the public release now. The download button will become the verified universal PKG the moment it is published.',
      secondary: 'View source repository',
    },
    footer: {
      tagline: 'AI post-production workspace for DaVinci Resolve.',
      product: 'Product',
      resources: 'Resources',
      legal: 'Legal',
      repository: 'Repository',
      releases: 'Releases',
      security: 'Security',
      license: 'License',
      notices: 'Third-party notices',
      rights: 'EasyField. All rights reserved.',
      trademark: 'EasyField is an independent product and is not affiliated with, endorsed by, or sponsored by Blackmagic Design. DaVinci Resolve is a trademark of Blackmagic Design Pty Ltd.',
    },
  },
  he: {
    languageLabel: 'English',
    nav: {
      product: 'המוצר',
      tools: '20 כלים',
      workflow: 'איך זה עובד',
      pricing: 'מחירים',
      faq: 'שאלות',
      cta: 'קבלו את EasyField',
      menu: 'פתיחת תפריט',
      close: 'סגירת תפריט',
    },
    hero: {
      eyebrow: 'בטא פרטית · תואם ל־DAVINCI RESOLVE STUDIO 21',
      titleLead: 'פלאגין AI ל־Resolve 21.',
      titleAccent: 'בנוי סביב הטיימליין.',
      body: 'EasyField הופך הקשר אמיתי מהעריכה — פריים מה־playhead, חיתוך נראה, גבולות שוטים ונכסים מהספרייה — לתהליכי תמונה, וידאו, מושן ואודיו שנבדקים לפני שרק התוצאה שאישרתם חוזרת ל־Resolve.',
      secondary: 'הכירו את סביבת העבודה',
      note: 'macOS 15+ · Resolve Studio 21.0.2+ · Apple silicon ו־Intel',
      status: 'הורדה שמתעדכנת אוטומטית',
    },
    release: {
      checking: 'בודק את הבנייה האחרונה…',
      available: 'הורדה ל־macOS',
      unavailable: 'מעקב אחרי ההפצה הציבורית',
      unavailableShort: 'סטטוס ההפצה',
      hintAvailable: 'חבילת PKG חתומה ואוניברסלית',
      hintUnavailable: 'חבילת ה־PKG הציבורית עדיין לא פורסמה',
    },
    proof: [
      { value: '20', label: 'כלים ייעודיים' },
      { value: '5', label: 'קטגוריות יצירה' },
      { value: '100', label: 'שפות לתמלול מקומי' },
      { value: '1', label: 'זרימה רציפה לטיימליין' },
    ],
    product: {
      eyebrow: 'התממשקות עם הטיימליין',
      title: 'הקשר מדויק נכנס. הצבה מכוונת יוצאת.',
      body: 'EasyField לוכד רק את המקור והתזמון שכל תהליך צריך, שומר כל תוצר בספרייה המקומית ומשאיר לעורך את ההחלטה הסופית.',
      labels: ['חיתוך נראה ומדויק', 'בדיקה לפני הצבה', 'קודם לספרייה המקומית'],
    },
    tools: {
      eyebrow: 'תהליך ייעודי, לא תיבת פרומפט',
      title: 'עשרים תהליכים ממוקדים. ממשק אחד מוכר.',
      body: 'עברו מסינון חומרי גלם לתמונות, שוטים חדשים, מושן, קריינות, סאונד ותזמון—בלי לבנות מחדש את ההקשר בכל אפליקציה.',
      categoryLabel: 'קטגוריית כלים',
      availability: 'זמינות הכלים תלויה בגרסה המותקנת ובמתאמים שאומתו.',
      total: 'תהליכים\n05 קטגוריות',
      count: 'כלים',
      review: 'בדיקה',
      workspace: 'סביבת עבודה',
    },
    workflow: {
      eyebrow: 'זרימה אחת, בשליטה מלאה',
      title: 'הקשר נכנס. תוצאה שנבדקה יוצאת.',
      body: 'EasyField משאיר את העורך בשליטה בכל שלב—מבחירת המקור, דרך בדיקת פרטיות ועלות ועד להצבה הסופית.',
      steps: [
        { index: '01', title: 'לוכדים הקשר מדויק', body: 'השתמשו בנקודת הניגון, בטווח מסומן, ב־Media Pool, בקובץ מקומי או בתוצאה מהספרייה.' },
        { index: '02', title: 'מכוונים את התהליך הנכון', body: 'בחרו מתכון ומודל מאומת, ואז הגדירו פרומפט, מקורות, משך ופלט.' },
        { index: '03', title: 'בודקים לפני שמשהו משתנה', body: 'רואים ספק, פרטיות, הערכת קרדיטים וכוונת הצבה לפני הרצה או החלה.' },
        { index: '04', title: 'שומרים ורק אז מציבים', body: 'התוצאות נכנסות קודם לספרייה המקומית. רק הגרסה שתבחרו חוזרת ל־Resolve.' },
      ],
    },
    brain: {
      eyebrow: 'SUPERBRAIN',
      title: 'אסטרטג לטיימליין—לא קופסה שחורה.',
      body: 'תארו את התוצאה הרצויה. SuperBrain הופך אותה לתכנית רב־כלית מובנית וניתנת לבדיקה, כדי שתוכלו לבחון כל שלב לפני שהרצה מלאה תתאפשר.',
      prompt: 'בנה טריילר של 30 שניות מהטווח המסומן. שמור על הדיאלוג, הוסף כתוביות עדינות והצע פסקול.',
      response: 'מיפיתי תהליך בן שלושה חלקים סביב הטווח שסימנת. בדקו מקורות, הצבה, פרטיות ועלות משוערת לפני הרצת כל כלי.',
      plan: [
        ['01', 'ניתוח הטווח המסומן', 'מקומי'],
        ['02', 'הכנת תהליך כתוביות', 'בדיקה'],
        ['03', 'טיוטת בריף לפסקול', 'ענן'],
      ],
      status: 'התכנית מוכנה לבדיקה',
      badge: 'דבר לא משתנה בלי אישור שלכם',
    },
    trust: {
      eyebrow: 'נבנה לעריכות אמיתיות',
      title: 'ענן כשזה מועיל. מקומי כשזה חשוב.',
      body: 'המוצר מבדיל בין תהליכים מקומיים, היברידיים וענניים, מגן על הגישה ל־Resolve באמצעות bridge מקומי, ושומר רישומי משימות ותוצרים עמידים על ה־Mac.',
      cards: [
        { title: 'עבודה מקומית ופרטית', body: 'תמלול וניתוח קצב מתוכננים לרוץ מקומית עם מנועים מנוהלים וניתנים לשימוש חוזר.' },
        { title: 'בדיקת ענן מפורשת', body: 'רואים מה מועלה, באיזה ספק משתמשים ומהי הערכת הקרדיטים לפני שמשימת ענן מתחילה.' },
        { title: 'הצבה לא־הרסנית', body: 'המדיה נוצרת ונבדקת לפני ייבוא או הוספה לטיימליין הפעיל.' },
      ],
      footnote: 'זמינות המוצר ואריזת המנועים תלויות בגרסת ההפצה. EasyField אינו מציג משימה בתשלום כהושלמה כאשר המתאם שלה אינו זמין.',
    },
    pricing: {
      eyebrow: 'הצצה למחירי ההשקה',
      title: 'תכנית לכל חדר עריכה.',
      body: 'אלו ערכי התכניות המתוכננים כרגע במוצר. התשלום אינו פעיל במהלך הבטא הפרטית.',
      monthly: 'חודשי',
      annual: 'שנתי',
      perMonth: '/ חודש',
      perYear: '/ שנה',
      credits: 'קרדיטים בכל חודש',
      allModels: 'כל משפחות המודלים המאומתות',
      starterModels: 'Seedance 2 Fast ו־Mini; ללא Seedance 2 הרגיל',
      topup: 'השלמת קרדיטים החל מ־$10',
      library: 'ספרייה מקומית ופעילות',
      billingLabel: 'תקופת חיוב',
      current: 'מומלץ',
      beta: 'יהיה זמין לאחר ההשקה הציבורית',
      partner: 'הצצה ל־Partner: ‏$999 בתשלום חד־פעמי, גישה לכל החיים, כל המודלים המאומתים וחשבון ספק משלכם. לא זמין בבטא הפרטית.',
    },
    install: {
      eyebrow: 'מוכן ליום ההשקה',
      title: 'מתקינים פעם אחת. נשארים בזרימה.',
      body: 'כאשר הבנייה הציבורית והמאומתת תפורסם, אותו כפתור הורדה באתר יעבור אוטומטית לחבילת ה־PKG האוניברסלית האחרונה.',
      steps: [
        { title: 'מורידים PKG אוניברסלי', body: 'מתקין אחד ל־Apple silicon ול־Intel, חתום ומאומת עבור macOS.' },
        { title: 'סוגרים את Resolve ומתקינים', body: 'המתקין בודק את מערכת ההפעלה ואת Resolve ומבצע התקנה אטומית של הפלאגין.' },
        { title: 'פותחים את EasyField ב־Resolve', body: 'פותחים פרויקט וטיימליין ואז בוחרים Workspace → Workflow Integrations → EasyField.' },
      ],
      requirements: 'דרישות מערכת',
      requirementItems: ['macOS 15 ומעלה', 'DaVinci Resolve Studio 21.0.2+', 'Resolve שהותקן ישירות מ־Blackmagic Design', 'הרשאת מנהל במהלך ההתקנה'],
      devNote: 'Node, Python, Homebrew ו־FFmpeg הם דרישות פיתוח—לא שלבי התקנה למשתמשים.',
    },
    faq: {
      eyebrow: 'שאלות ותשובות',
      title: 'לפני שמניחים את זה על הטיימליין.',
      items: [
        { q: 'האם אפשר להוריד את EasyField כבר עכשיו?', a: 'האתר בודק את GitHub Releases בזמן אמת. כרגע חבילת ה־PKG הציבורית והחתומה טרם פורסמה, ולכן הפעולה פותחת את סטטוס ההפצה. ברגע שתהיה גרסה מאומתת היא תהפוך אוטומטית להורדה ישירה ל־macOS.' },
        { q: 'האם זה עובד עם הגרסה החינמית של DaVinci Resolve?', a: 'היעד הנוכחי הוא DaVinci Resolve Studio 21.0.2 ומעלה על macOS 15+. גרסת ה־Mac App Store אינה נתמכת על ידי המתקין המתוכנן.' },
        { q: 'האם כל כלי מעלה את חומרי הגלם שלי?', a: 'לא. EasyField מבדיל בין תהליכים מקומיים, היברידיים וענניים. לפני שמשהו יוצא מה־Mac אמורה להופיע בדיקת פרטיות והעלאה.' },
        { q: 'האם SuperBrain עורך את הטיימליין אוטומטית?', a: 'לא במצב המוצר הנוכחי. SuperBrain בונה ומאמת תכנית רב־כלית לבדיקה. החלה מלאה נשארת חסומה עד שכל שלב חושף עלות, פרטיות, ספק, הצבה ואפשרות שחזור.' },
        { q: 'לאן מגיעות התוצאות שנוצרו?', a: 'תוצאות שהתקבלו נשמרות קודם בספריית EasyField המקומית. לאחר מכן בוחרים מה להוריד, לשלוח ל־Media Pool או להציב בטיימליין הפעיל.' },
        { q: 'אילו כלים כלולים?', a: 'הקטלוג הנוכחי כולל 20 תהליכים בקטגוריות Footage, Image, Video, Motion ו־Audio. תהליכים חדשים יותר עשויים לעצור בבדיקת preflight אמיתית עד שהמתאם המאומת שלהם ייכלל בגרסה המותקנת.' },
      ],
    },
    closing: {
      eyebrow: 'מרעיון לטיימליין הסופי',
      title: 'ההחלטה היצירתית נשארת במקום הנכון—אצל העורך.',
      body: 'עקבו עכשיו אחרי ההפצה הציבורית. כפתור ההורדה יהפוך לחבילת ה־PKG האוניברסלית והמאומתת ברגע שהיא תפורסם.',
      secondary: 'צפייה במאגר הקוד',
    },
    footer: {
      tagline: 'סביבת AI לפוסט־פרודקשן בתוך DaVinci Resolve.',
      product: 'המוצר',
      resources: 'משאבים',
      legal: 'משפטי',
      repository: 'מאגר',
      releases: 'הפצות',
      security: 'אבטחה',
      license: 'רישיון',
      notices: 'הודעות צד שלישי',
      rights: 'EasyField. כל הזכויות שמורות.',
      trademark: 'EasyField הוא מוצר עצמאי ואינו קשור, מאושר או ממומן על ידי Blackmagic Design. ‏DaVinci Resolve הוא סימן מסחר של Blackmagic Design Pty Ltd.',
    },
  },
} as const

export const toolCategories = [
  {
    id: 'footage',
    color: '#9BA3B5',
    names: { en: 'Footage', he: 'חומרי גלם' },
    description: { en: 'Review, cover and enhance source media.', he: 'בדיקה, השלמת כיסוי ושיפור חומרי מקור.' },
    tools: ['Culling', 'B-roll', 'Upscale'],
  },
  {
    id: 'image',
    color: '#E26BD2',
    names: { en: 'Image', he: 'תמונה' },
    description: { en: 'Create consistent frames, boards and characters.', he: 'יצירת פריימים, סטוריבורדים ודמויות עקביות.' },
    tools: ['Create Image', 'Storyboard', 'Character', 'Edit Image', 'Angles'],
  },
  {
    id: 'video',
    color: '#6F95FF',
    names: { en: 'Video', he: 'וידאו' },
    description: { en: 'Generate, transform, extend and bridge shots.', he: 'יצירה, שינוי, הארכה וחיבור של שוטים.' },
    tools: ['Create Video', 'Avatar', 'Edit Video', 'Extend Video', 'Transition'],
  },
  {
    id: 'motion',
    color: '#FFBD6A',
    names: { en: 'Motion', he: 'מושן' },
    description: { en: 'Build animations and reviewed captions.', he: 'בניית אנימציות וכתוביות שנבדקו.' },
    tools: ['Animations', 'Captions'],
  },
  {
    id: 'audio',
    color: '#42DFA2',
    names: { en: 'Audio', he: 'אודיו' },
    description: { en: 'Score, narrate, transcribe and find the beat.', he: 'פסקול, קריינות, תמלול וזיהוי קצב.' },
    tools: ['Create Music', 'Sound Effects', 'Voice Over', 'Transcribe', 'Beat Detection'],
  },
] as const

export const pricingPlans = [
  { id: 'starter', name: 'Starter', monthly: 15, annual: 144, credits: '800', recommended: false },
  { id: 'creator', name: 'Creator', monthly: 24, annual: 300, credits: '2,000', recommended: true },
  { id: 'pro', name: 'Pro', monthly: 60, annual: 588, credits: '5,000', recommended: false },
  { id: 'studio', name: 'Studio', monthly: 129, annual: 1188, credits: '12,000', recommended: false },
] as const
