import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { createUnavailableAccountSnapshot } from '../src/core/accountBridge.ts'
import { host } from '../src/services/host.ts'
import { ACCOUNT_API_KEY_TOKEN } from '../src/settings.ts'

const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const accountSource = readFileSync(new URL('../src/screens/Account.tsx', import.meta.url), 'utf8')
const accountCss = readFileSync(new URL('../src/account.css', import.meta.url), 'utf8')
const homeSource = readFileSync(new URL('../src/screens/Home.tsx', import.meta.url), 'utf8')
const settingsSource = readFileSync(new URL('../src/screens/SettingsScreen.tsx', import.meta.url), 'utf8')
const preloadTypes = readFileSync(new URL('../src/vite-env.d.ts', import.meta.url), 'utf8')
const accountBridgeSource = readFileSync(new URL('../src/core/accountBridge.ts', import.meta.url), 'utf8')

test('an unconfigured renderer bridge fails closed instead of creating a local account session', async () => {
  const snapshot = createUnavailableAccountSnapshot()
  assert.deepEqual(snapshot.session, { status: 'signed-out' })
  assert.equal(snapshot.checkoutStatus, null)
  assert.deepEqual(snapshot.capabilities, {
    accountConfigured: false,
    billingConfigured: false,
    oauthProviders: [],
    generationAccess: false,
    directProviderAllowed: false,
    customerCheckoutAvailable: false,
    partnerCheckoutAvailable: false,
    billingPortalAvailable: false,
  })

  const restored = await host.account.restore()
  assert.equal(restored.ok, false)
  if (!restored.ok) assert.equal(restored.error.code, 'service-unavailable')
})

test('account configuration, runtime health and last successful refresh remain distinct', () => {
  assert.match(accountBridgeSource, /export type AccountServiceHealth = 'checking' \| 'available' \| 'unavailable' \| 'unconfigured'/)
  assert.match(appSource, /useState<AccountServiceHealth>\('checking'\)/)
  assert.match(appSource, /setAccountServiceHealth\('available'\)/)
  assert.match(appSource, /setAccountServiceHealth\(unconfigured \? 'unconfigured' : 'unavailable'\)/)
  assert.match(appSource, /lastSuccessfulAccountRefreshAtMs/)
  assert.match(appSource, /markAccountServiceFailure\(result\.error, true\)/)
  assert.match(accountSource, /Configured service is offline/)
  assert.match(accountSource, /Last successful refresh/)
  assert.match(settingsSource, /accountServiceHealth === 'unavailable'[\s\S]*Account service offline/)
  assert.match(settingsSource, /Promise\.resolve\(onRefreshAccount\(\)\)/)
  assert.doesNotMatch(accountSource, /capabilities\.accountConfigured/)
  assert.doesNotMatch(homeSource, /accountConfigured/)
  assert.doesNotMatch(settingsSource, /accountConfigured/)
})

test('Account is a real application route backed by the narrow account host wrapper', () => {
  assert.match(appSource, /type Screen = [^\n]*'account'/)
  assert.match(appSource, /screen === 'account' && \(/)
  assert.match(appSource, /host\.account\.restore\(\)/)
  assert.match(appSource, /host\.account\.onChanged/)
  assert.match(appSource, /host\.account\.onOAuthCompleted/)
  assert.match(appSource, /host\.account\.onPasswordRecoveryCompleted/)
  assert.match(appSource, /host\.account\.requestPasswordReset/)
  assert.match(appSource, /host\.account\.completePasswordRecovery/)
  assert.match(appSource, /host\.account\.updateProfile/)
  assert.match(preloadTypes, /account\?: import\('\.\/core\/accountBridge'\)\.AccountBridgeApi/)
  assert.match(preloadTypes, /directCloud\?: \{[\s\S]*connect: \(candidate: string\) => Promise<\{ credits: number \}>/)
  assert.match(preloadTypes, /directCloud\?: \{[\s\S]*hasExisting: \(\) => Promise<boolean>/)
  assert.match(preloadTypes, /directCloud\?: \{[\s\S]*hasScoped: \(\) => Promise<boolean>/)
  assert.match(preloadTypes, /directCloud\?: \{[\s\S]*adoptExisting: \(\) => Promise<\{ credits: number \}>/)
  assert.match(accountSource, /const configuredOAuthProviders = Array\.isArray\(props\.capabilities\.oauthProviders\)/)
  assert.match(accountSource, /googleOAuthAvailable && \([\s\S]*onRequestGoogleAuth/)
  assert.match(accountSource, /appleOAuthAvailable && \([\s\S]*onRequestAppleAuth/)
  assert.match(accountSource, /socialAuthAvailable && \([\s\S]*ef-account-divider[\s\S]*ef-account-socials/)
})

test('runtime generation sentinels are capability-gated by the Main snapshot', () => {
  assert.equal(ACCOUNT_API_KEY_TOKEN, '__easyfield_account__')
  assert.match(appSource, /if \(accountSnapshot\.capabilities\.directProviderAllowed\) \{[\s\S]*SECURE_API_KEY_TOKEN/)
  assert.match(appSource, /if \(accountSnapshot\.capabilities\.generationAccess\) \{[\s\S]*setCurrentApiKey\(ACCOUNT_API_KEY_TOKEN\)/)
  assert.match(appSource, /if \(!accountSnapshot\.capabilities\.directProviderAllowed\) \{[\s\S]*Direct provider access is not available/)
  assert.match(appSource, /Admin and Partner use only their own direct account[\s\S]*setCurrentApiKey\(''\)[\s\S]*return/)
  assert.match(appSource, /host\.connectDirectCloudCredential\(candidate\)/)
  assert.match(appSource, /host\.adoptExistingDirectCloudCredential\(\)/)
  assert.match(appSource, /host\.hasExistingDirectCloudCredential\(\)/)
  assert.match(appSource, /candidate === SECURE_API_KEY_TOKEN[\s\S]*refreshCredits\(SECURE_API_KEY_TOKEN, isCurrent\)[\s\S]*return/)
  assert.match(appSource, /const generationReady = directProviderAllowed[\s\S]*apiStatus === 'connected'/)
})

test('regular users reach Account and cannot see direct-provider credential controls', () => {
  assert.match(homeSource, /directProviderAllowed && settingsOpen && \(/)
  assert.match(homeSource, /onClick=\{directProviderAllowed \? toggleApiSettings : onOpenAccount\}/)
  assert.match(homeSource, /onOpenAccount/)
  assert.match(settingsSource, /directProviderAllowed \? \(/)
  assert.match(settingsSource, /Regular users never enter a provider key\./)
  assert.match(homeSource, /hasExistingDirectCredential && apiStatus !== 'connected'/)
  assert.match(settingsSource, /hasExistingDirectCredential && apiStatus !== 'connected'/)
  assert.match(homeSource, /Use saved Mac connection/)
  assert.match(settingsSource, /Use saved Mac connection/)
})

test('signed-in Account provides a role-aware personal area at compact and expanded widths', () => {
  for (const section of ['overview', 'profile', 'billing', 'credits', 'security', 'connections']) {
    assert.match(accountSource, new RegExp(`id: '${section}'`), section)
  }
  assert.match(accountSource, /role="tablist" aria-label="Account sections"/)
  assert.match(accountSource, /role="tab"[\s\S]*aria-selected=\{section === item\.id\}/)
  assert.match(accountSource, /aria-controls="ef-account-panel"/)
  assert.match(accountSource, /role="tabpanel"[\s\S]*id="ef-account-panel"[\s\S]*aria-labelledby=\{`ef-account-tab-\$\{section\}`\}/)
  assert.match(accountSource, /\['ArrowDown', 'ArrowUp', 'ArrowRight', 'ArrowLeft', 'Home', 'End'\]/)
  assert.match(accountSource, /useEffect\(\(\) => setSection\('overview'\), \[signedInAccountId\]\)/)
  assert.match(accountSource, /contentRef\.current\.scrollTop = 0/)
  assert.match(accountSource, /window\.matchMedia\?\.\('\(min-width: 700px\)'\)/)
  assert.match(accountSource, /ef-account-signout[\s\S]*authPending \? 'Signing out…' : 'Sign out'/)
  assert.match(accountCss, /\.ef-account-nav-items\s*\{[\s\S]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
  assert.match(accountCss, /@media \(min-width: 700px\)[\s\S]*\.ef-account-layout\s*\{[\s\S]*grid-template-columns: 210px minmax\(0, 1fr\)/)
  assert.match(accountCss, /\.ef-account-signout\s*\{[\s\S]*min-height: 44px/)
  assert.match(accountCss, /\.ef-account-nav-copy strong \{[^\n]*font-size: 12px/)
  assert.match(accountCss, /\.ef-account-section-head > div > small\s*\{[\s\S]*font-size: 11px/)
})

test('Connections exposes only real optional management actions and confirms direct disconnect inline', () => {
  assert.match(accountSource, /onOpenSettings\?: \(\) => void/)
  assert.match(accountSource, /onDisconnectDirectConnection\?: \(\) => void \| Promise<void>/)
  assert.match(accountSource, /directConnectionPresent\?: boolean/)
  assert.match(accountSource, /directPresent && props\.onDisconnectDirectConnection && !confirmDisconnect/)
  assert.match(accountSource, /directPresent && !directAllowed \? 'Saved · access unavailable'/)
  assert.match(accountSource, /Disconnect this Mac\?/)
  assert.match(accountSource, /Confirm disconnect/)
  assert.doesNotMatch(accountSource, /window\.confirm/)
  assert.match(accountCss, /\.ef-account-disconnect-confirm > button \{[^}]*min-height: 44px/)
  assert.match(appSource, /directConnectionPresent=\{hasScopedDirectCredential\}/)
  assert.match(appSource, /host\.hasCurrentAccountDirectCloudCredential\(\)/)
  assert.doesNotMatch(appSource, /directConnectionPresent=\{[^}]*hasExistingDirectCredential/)
  assert.match(appSource, /onDisconnectDirectConnection=\{disconnectDirectConnection\}/)
  assert.match(accountSource, /keepConnectedButtonRef\.current\?\.focus\(\)/)
  assert.match(accountSource, /activeJobCount[\s\S]*before disconnecting/)
})

test('Account keeps privileged admin billing separate from customer purchases', () => {
  assert.match(accountSource, /const isAdmin = signedInSession\?\.platformRole === 'admin'/)
  assert.match(accountSource, /const isSupport = signedInSession\?\.platformRole === 'support'/)
  assert.match(accountSource, /const showCustomerBilling = signedInSession\?\.platformRole === 'customer' && !activePartner/)
  assert.match(accountSource, /signedInSession\.platformRole === 'customer' && <PartnerMembershipSection/)
  assert.match(accountSource, /isSupport && <SupportCreditsSection/)
  assert.match(accountSource, /isSupport\s*\? 'Support workspace access'/)
  assert.match(accountSource, /!isAdmin && !isSupport && !activePartner/)
  assert.match(accountSource, /!isSupport && <button[^>]*onClick=\{\(\) => onSectionChange\('credits'\)\}/)
  assert.match(accountSource, /isSupport \? 'No customer wallet'/)
  assert.match(accountSource, /\{showCustomerBilling && <BalanceSection/)
  assert.match(accountSource, /\{showCustomerBilling && <PlansSection/)
  assert.match(accountSource, /\{showCustomerBilling && <TopUpSection/)
  assert.match(accountSource, /\{showCustomerBilling && <AutoReloadSection/)
  assert.match(appSource, /directProviderCredits=\{directProviderAllowed \? apiCredits : null\}/)
  assert.match(accountSource, /if \(session\.status !== 'signed-in' \|\| !session\.emailVerified \|\| !directProviderAllowed\) return null/)
  assert.match(accountSource, /snapshot\?\.upstreamBalanceCreditMicros == null[\s\S]*localBalance[\s\S]*formatCreditMicros\(snapshot\.upstreamBalanceCreditMicros\)/)
  assert.match(accountSource, /LATEST RAW COST[\s\S]*snapshot\?\.latestRawCostMoneyMicros/)
  assert.doesNotMatch(accountSource, /LATEST RAW COST[\s\S]{0,300}directProviderCredits/)
})

test('Account checkout recovery is explicit and sign-up requires a useful password length', () => {
  // Pinned to the shared constant rather than a literal: the minimum tracks the
  // deployed Supabase policy, and a number written here would silently disagree
  // with it the next time that policy moves.
  assert.match(accountSource, /import \{\n\s*MIN_PASSWORD_LENGTH,/)
  assert.match(accountSource, /minLength=\{signUp \? MIN_PASSWORD_LENGTH : undefined\}/)
  assert.match(accountSource, /Use at least \{MIN_PASSWORD_LENGTH\} characters\./)
  // Scoped to password inputs — other fields legitimately carry a literal
  // minLength, and sweeping them in would make this assertion mean nothing.
  assert.doesNotMatch(accountSource, /type="password"[^>]*minLength=\{\s*\d/, 'password inputs must size from the shared constant')
  assert.match(accountSource, /Forgot password\?/)
  assert.match(accountSource, /SECURE PASSWORD RECOVERY/)
  assert.match(accountSource, /onCompletePasswordRecovery/)
  assert.match(accountSource, /onCancelPasswordRecovery/)
  assert.match(accountSource, /Send reset email/)
  assert.match(accountSource, /onRequestRefreshAccount/)
  assert.match(accountSource, /onDismissCheckoutStatus\?: \(\) => void/)
  assert.match(accountSource, /checkoutStatus\.state === 'completed' \|\| checkoutStatus\.state === 'closed-unpaid'[\s\S]*onDismissCheckoutStatus/)
  assert.match(appSource, /host\.account\.getSnapshot\(\{ force: true \}\)/)
  assert.match(appSource, /Payment has not been confirmed yet[\s\S]*Refresh account/)
  assert.match(appSource, /checkoutStatus/)
  assert.match(appSource, /const visibleCheckoutStatus = currentCheckoutStatusMarker[\s\S]*currentCheckoutStatusMarker !== dismissedCheckoutStatusMarker[\s\S]*accountSnapshot\.checkoutStatus/)
  assert.match(appSource, /checkoutStatus=\{visibleCheckoutStatus\}/)
  assert.match(appSource, /onDismissCheckoutStatus=\{\(\) => \{[\s\S]*setDismissedCheckoutStatusMarker\(checkoutStatusMarker\(visibleCheckoutStatus\)\)/)
  assert.match(accountSource, /capabilities\.customerCheckoutAvailable/)
  assert.match(accountSource, /capabilities\.partnerCheckoutAvailable/)
  assert.match(homeSource, /Review your plan, balance or verification status to enable generation\./)
  assert.match(settingsSource, /Review your plan, balance or verification status\./)
})

test('purchase controls expose clear selection, loading and validation states at both panel widths', () => {
  assert.match(accountSource, /ef-account-interval" role="group" aria-label="Billing interval"/)
  assert.match(accountSource, /aria-pressed=\{props\.billingInterval === 'annual'\}/)
  assert.match(accountSource, /aria-label=\{accessibleLabel\}/)
  assert.match(accountSource, /ef-account-checkout-due/)
  assert.match(accountSource, /label htmlFor=\{inputId\}/)
  assert.match(accountSource, /aria-invalid=\{Boolean\(validation\) \|\| undefined\}/)
  assert.match(accountSource, /ef-account-quote" role="status" aria-live="polite"/)
  assert.match(accountSource, /const automaticCharge = policy\.enabled[\s\S]*quoteTopUp\(props\.pricingPlanId, policy\.topUpAmountCreditMicros\)/)
  assert.match(accountSource, /Saving authorizes this charge for each automatic reload\./)
  assert.match(accountSource, /aria-busy=\{props\.topUpPending \|\| undefined\}/)
  assert.match(accountCss, /\.ef-account-plan-grid\s*\{[\s\S]*?grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(accountCss, /@media \(max-width: 460px\)[\s\S]*?\.ef-account-plan-grid \{ grid-template-columns: minmax\(0, 1fr\); \}/)
  assert.match(accountCss, /\.ef-account-switch \{ width: 50px; height: 44px;/)
  assert.match(accountCss, /--account-control-line: rgba\(255, 255, 255, \.34\)/)
  assert.match(accountCss, /\.ef-account-nav \{[\s\S]*grid-template-areas:[\s\S]*'identity signout'[\s\S]*'tabs tabs'/)
  assert.match(accountCss, /@media \(min-width: 700px\)[\s\S]*\.ef-account-nav \{[\s\S]*overflow-y: auto/)
  assert.match(accountCss, /\.ef-account-back \{[\s\S]*?width: 44px;[\s\S]*?height: 44px;/)
  assert.match(accountCss, /\.ef-account-identity > button,[\s\S]*?\.ef-account-autoreload-controls > button \{[\s\S]*?min-width: 44px;[\s\S]*?min-height: 44px;/)
  assert.match(accountCss, /\.ef-account-auth-tabs button \{[\s\S]*?min-width: 44px;[\s\S]*?min-height: 44px;/)
  assert.match(accountCss, /\.ef-account-socials button \{[\s\S]*?min-width: 44px;[\s\S]*?min-height: 44px;/)
  assert.match(accountCss, /\.ef-account-refresh > button \{[\s\S]*?min-width: 44px;[\s\S]*?min-height: 44px;/)
  assert.match(accountCss, /@media \(max-width: 460px\)[\s\S]*?\.ef-account-identity > button \{ min-width: 44px; min-height: 44px;/)
  assert.match(accountCss, /@media \(max-width: 380px\)[\s\S]*?\.ef-account-back \{ width: 44px; height: 44px; \}/)
})

test('missing, loading, stale and zero-capable balance states stay distinguishable and refreshable', () => {
  assert.match(accountSource, /if \(serviceHealth === 'checking'\) return 'Checking…'/)
  assert.match(accountSource, /if \(serviceHealth === 'available'\) return 'Not reported'/)
  assert.match(accountSource, /The latest account refresh returned no balance data\./)
  assert.match(accountSource, /Balance data is unavailable while the account service is offline\./)
  assert.match(accountSource, /balances \? formatCreditMicros\(balances\.subscriptionCreditMicros\) : unavailableValue/)
  assert.match(accountSource, /balances \? formatCreditMicros\(balances\.purchasedCreditMicros\) : unavailableValue/)
  assert.match(accountSource, /Refresh balance/)
  assert.match(accountSource, /Balance measured \$\{formatAccountDate\(balances\.measuredAtMs\)\}/)
})

test('account actions show accurate browser handoff states and resume pending checkout monitoring', () => {
  assert.match(appSource, /Billing portal opened in your browser\. Return here and refresh your account after making changes\./)
  assert.match(appSource, /Provider credit purchase opened in your browser\. Return here and refresh your balance after purchase\./)
  assert.match(appSource, /const checkoutStatus = result\.value\.checkoutStatus[\s\S]*checkoutStatus\?\.state === 'pending'[\s\S]*watchPendingCheckout\(checkoutStatus\)/)
  assert.match(accountSource, /disabled=\{authPending \|\| activeJobCount > 0\}/)
  assert.match(accountSource, /authPending \? 'Signing out…' : 'Sign out'/)
  assert.match(accountSource, /const unresolvedCheckout = Boolean\([\s\S]*props\.checkoutResumePending[\s\S]*props\.planCheckoutPending[\s\S]*props\.topUpPending[\s\S]*props\.partnerCheckoutPending[\s\S]*props\.checkoutStatus\?\.state === 'pending'[\s\S]*props\.checkoutStatus\?\.state === 'ready-to-resume'[\s\S]*props\.checkoutStatus\?\.state === 'awaiting-reconciliation'[\s\S]*\)/)
  assert.match(accountSource, /billingLocked = [^\n]*\|\| unresolvedCheckout/)
  assert.match(accountSource, /partnerBillingLocked = [^\n]*\|\| unresolvedCheckout/)
  assert.match(accountSource, /portalLocked = [^\n]*\|\| unresolvedCheckout/)
  assert.match(accountSource, /Check payment status/)
  assert.match(appSource, /ef-account-recovery-notice/)
  assert.match(appSource, /Account refreshed\. Your checkout is still open\./)
  assert.match(appSource, /const requestResumeCheckout = useCallback[\s\S]*setAccountRefreshFeedback\(null\)[\s\S]*if \(!result\.ok\)[\s\S]*setAccountRefreshFeedback\(feedback\)[\s\S]*const reopenedFeedback:[\s\S]*setAccountRefreshFeedback\(reopenedFeedback\)/)
  assert.match(accountSource, /accountRefreshFeedback && <Feedback value=\{accountRefreshFeedback\}/)
})

test('account identity changes clear private UI state and OAuth always reaches a terminal renderer state', () => {
  assert.match(appSource, /accountIdentityRef\.current !== nextAccountId/)
  assert.match(appSource, /setTopUpCredits\(''\)/)
  assert.match(appSource, /setPlanFeedback\(null\)/)
  assert.match(appSource, /setPartnerFeedback\(null\)/)
  assert.match(appSource, /setApiCredits\(null\)[\s\S]*setCurrentApiKey\(''\)/)
  assert.match(appSource, /accountRuntimeIdentity/)
  assert.match(appSource, /const refreshCredits = useCallback\(async \(key: string, isCurrent: \(\) => boolean[\s\S]*if \(!isCurrent\(\)\) return false[\s\S]*const r = await fetchCredits\(key\)[\s\S]*if \(!isCurrent\(\)\) return false/)
  assert.match(appSource, /refreshCredits\(SECURE_API_KEY_TOKEN, \(\) => accountUiEpochRef\.current === uiEpoch\)/)
  assert.match(appSource, /apiCredits \?\? \(accountSnapshot\.capabilities\.accountConfigured \? 0 : credits\)/)
  assert.match(appSource, /useState<BillingInterval>\(DEFAULT_BILLING_INTERVAL\)/)
  assert.match(appSource, /if \(next === 'account'\) setBillingInterval\(DEFAULT_BILLING_INTERVAL\)/)
  assert.doesNotMatch(appSource, /setBillingInterval\(snapshot\.subscription\.billingInterval\)/)
  assert.match(appSource, /accountOAuthAttemptRef\.current = result\.value\.attemptId/)
  assert.match(appSource, /Social sign-in expired\. Try again\./)
  assert.match(accountSource, /props\.authFeedback && <Feedback value=\{props\.authFeedback\}/)
  assert.match(accountSource, /Partner lifetime access/)
  assert.match(accountSource, /onRequestProfileUpdate/)
  assert.match(accountSource, /Plan changes and cancellation are handled through Manage billing\./)
  assert.match(accountSource, /props\.managedSubscription \? 'Manage current plan'/)
})
