// The media library — raw footage plus everything generated by the tools,
// grouped by category. Mock data stands in until wired to the Resolve Media
// Pool + real generation jobs.

export type AssetKind = 'image' | 'video' | 'audio'

export interface Asset {
  id: string
  name: string
  category: string
  kind: AssetKind
  meta: string // timecode, duration, or resolution
}

export interface LibraryCategory {
  id: string
  label: string
  color: string
  kind: AssetKind
  assets: Asset[]
}

export const LIBRARY: LibraryCategory[] = [
  {
    id: 'footage',
    label: 'Footage',
    color: '#9BA3B5',
    kind: 'video',
    assets: [
      { id: 'f1', name: 'Interview A-cam', category: 'Footage', kind: 'video', meta: '02:14' },
      { id: 'f2', name: 'B-roll rooftop', category: 'Footage', kind: 'video', meta: '00:48' },
      { id: 'f3', name: 'Street timelapse', category: 'Footage', kind: 'video', meta: '01:02' },
      { id: 'f4', name: 'Product spin raw', category: 'Footage', kind: 'video', meta: '00:36' },
    ],
  },
  {
    id: 'images',
    label: 'Images',
    color: '#E26BD2',
    kind: 'image',
    assets: [
      { id: 'i1', name: 'Vinyl macro', category: 'Images', kind: 'image', meta: '2K' },
      { id: 'i2', name: 'Neon street key', category: 'Images', kind: 'image', meta: '4K' },
      { id: 'i3', name: 'Studio portrait', category: 'Images', kind: 'image', meta: '2K' },
      { id: 'i4', name: 'Storyboard 01', category: 'Images', kind: 'image', meta: '1K' },
      { id: 'i5', name: 'Product hero', category: 'Images', kind: 'image', meta: '4K' },
    ],
  },
  {
    id: 'videos',
    label: 'Videos',
    color: '#5B8CFF',
    kind: 'video',
    assets: [
      { id: 'v1', name: 'Neon push-in', category: 'Videos', kind: 'video', meta: '00:08' },
      { id: 'v2', name: 'Talking head grade', category: 'Videos', kind: 'video', meta: '00:12' },
      { id: 'v3', name: 'Logo morph', category: 'Videos', kind: 'video', meta: '00:05' },
      { id: 'v4', name: 'Drone continue', category: 'Videos', kind: 'video', meta: '00:10' },
    ],
  },
  {
    id: 'audio',
    label: 'Audio',
    color: '#3ED598',
    kind: 'audio',
    assets: [
      { id: 'a1', name: 'Cinematic score', category: 'Audio', kind: 'audio', meta: '01:20' },
      { id: 'a2', name: 'VO — trailer', category: 'Audio', kind: 'audio', meta: '00:22' },
      { id: 'a3', name: 'Rain foley', category: 'Audio', kind: 'audio', meta: '00:45' },
    ],
  },
]

export const LIBRARY_COUNT = LIBRARY.reduce((n, c) => n + c.assets.length, 0)

export function searchLibrary(query: string): LibraryCategory[] {
  const q = query.trim().toLowerCase()
  if (!q) return LIBRARY
  return LIBRARY.map((cat) => ({
    ...cat,
    assets: cat.assets.filter(
      (a) => a.name.toLowerCase().includes(q) || a.category.toLowerCase().includes(q),
    ),
  })).filter((cat) => cat.assets.length > 0)
}
